Repository cdktf/cdktf-multi-stack-tfe, pull requests merged in 2023-08, with the labels that each got.

#134 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#135 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#136 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#137 chore(ci): remove Mergify
  .gitattributes
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/pull-request-lint.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .gitignore
  .mergify.yml
  .npmignore
  .projen/files.json
  .projenrc.ts
  projenrc/auto-approve.ts
  projenrc/automerge.ts
  projenrc/customized-license.ts
Labels: auto-approve, automerge

#138 feat: upgrade to jsii 5.1.x
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: auto-approve, automerge

#139 chore: try Dependabot for security updates
  .github/dependabot.yml
  .github/workflows/auto-approve.yml
  projenrc/auto-approve.ts
  yarn.lock
Labels: auto-approve, automerge

#142 chore!: upgrade to cdktf 0.18.0
  .github/workflows/upgrade-cdktf.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  projenrc/upgrade-cdktf.ts
  test/multi-stack-tfe.test.ts
  yarn.lock
Labels: auto-approve, automerge, dependencies

#144 chore(ci): fix link in upgrade script
  .github/workflows/upgrade-cdktf.yml
  projenrc/upgrade-cdktf.ts
Labels: auto-approve, automerge

#146 chore: update jsii-docgen
  .projen/deps.json
  .projenrc.ts
  API.md
  package.json
  yarn.lock
Labels: auto-approve, automerge

#147 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#148 chore: remove hard-coded dependency on jsii-docgen
  .projen/deps.json
  .projenrc.ts
Labels: auto-approve, automerge
