Repository cdktf/cdktf-multi-stack-tfe, pull requests merged in 2025-01, with the labels that each got.

#232 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#233 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, automerge, dependencies

#234 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-main.yml
  .projenrc.ts
Labels: auto-approve, automerge

#235 chore(ci): add workflow for upgrading jsii & typescript
  .gitattributes
  .github/workflows/upgrade-jsii-typescript.yml
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/upgrade-jsii-typescript.ts
  scripts/update-jsii-typescript.sh
  yarn.lock
Labels: auto-approve, automerge

#236 chore: upgrade jsii & typescript to v5.5
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: auto-approve, automerge, automated

#237 docs: create maintenance guide
  .github/MAINTENANCE.md
Labels: auto-approve, automerge

#239 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#240 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, automerge, dependencies

#241 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, automerge, dependencies
